'use strict';
const $ = (s) => document.querySelector(s);
const seasons = {fall:{name:'Fall 2026',date:'SUN, SEP 13',label:'NEXT GAME',time:'10:00 AM ET · Sample matchup',result:'SEP 06 · FINAL / 7',score:[8,3],record:[[4,1],[3,2],[3,2],[2,3],[1,4]],avg:'.500'},spring:{name:'Spring 2026',date:'SUN, JUN 14',label:'ARCHIVED GAME',time:'10:00 AM ET · Sample archive',result:'JUN 07 · FINAL / 7',score:[6,2],record:[[12,4],[10,6],[9,7],[6,10],[3,13]],avg:'.450'},history:{name:'2025 History',date:'2025 SEASON',label:'CHAMPIONSHIP ARCHIVE',time:'Champions · Game details pending',result:'2025 · SAMPLE FINAL / 7',score:[5,2],record:[[14,2],[11,5],[8,8],[5,11],[2,14]],avg:'.550'}};
const teams=['Jersey Dodgers','Jersey Braves','Big Apple Yankees','Brick City Rockies','Blue Angels'];
let current='spring', stat='batting';
function rows(){return seasons[current].record.map(([w,l],i)=>`<tr class="${i===0?'dodgers-row':''}"><td><span class="team-rank">0${i+1}</span>${teams[i]}</td><td>${w}</td><td>${l}</td><td>${(w/(w+l)).toFixed(3).replace(/^0/,'')}</td><td>${i?seasons[current].record[0][0]-w:'—'}</td></tr>`).join('')}
function renderLeaders(){const offset=current==='fall'?0:current==='spring'?1:2;const values=stat==='batting'?[['BATTING AVERAGE',['.429','.412','.438'][offset],'Alex Rivera','24 · OF'],['HOME RUNS',[3,6,8][offset],'Marcus Torres','17 · 1B'],['RUNS BATTED IN',[12,24,31][offset],'Daniel Cruz','9 · SS'],['STOLEN BASES',[7,13,16][offset],'Chris Bennett','2 · CF']]:[['EARNED RUN AVG',['1.75','2.10','1.62'][offset],'Luis Santos','31 · RHP'],['STRIKEOUTS',[28,62,71][offset],'Luis Santos','31 · RHP'],['WINS',[3,7,8][offset],'Mike Rossi','12 · LHP'],['WHIP',['0.94','1.08','0.98'][offset],'Mike Rossi','12 · LHP']];$('#leader-grid').innerHTML=values.map(([label,value,name,no])=>`<button class="leader-card" data-player="${name}"><span>${label}</span><b>${value}</b><strong>${name} ↗</strong><small>${no} · Sample player</small><span class="jersey-no" aria-hidden="true">${no.split(' ')[0]}</span></button>`).join('');}
function renderSeason(){const s=seasons[current];$('#game-label').textContent=`${s.label} · ${s.name.toUpperCase()}`;$('#game-date').textContent=s.date;$('#game-time').textContent=s.time;renderScores();$('#standings-season').textContent=s.name.toUpperCase();$('.season-copy').textContent=s.name;$('#standings-rows').innerHTML=rows();$('#hot-average').textContent=s.avg;$('#hot-hits').textContent=current==='fall'?10:current==='spring'?9:11;renderLeaders();}
$('#season').addEventListener('change',e=>{current=e.target.value;renderSeason()});
document.querySelectorAll('[data-stat]').forEach(button=>button.addEventListener('click',()=>{stat=button.dataset.stat;document.querySelectorAll('[data-stat]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button))});renderLeaders()}));
$('.menu-button').addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');$('.menu-button').setAttribute('aria-expanded',String(open))});
$('#navigation').addEventListener('click',e=>{if(e.target.closest('a,button')){$('#navigation').classList.remove('open');$('.menu-button').setAttribute('aria-expanded','false')}});
function recentGames(){const s=seasons[current];const dates=current==='spring'?['JUN 07','MAY 31','MAY 24','MAY 17','MAY 10']:current==='fall'?['SEP 06','AUG 30','AUG 23','AUG 16','AUG 09']:['2025 · G5','2025 · G4','2025 · G3','2025 · G2','2025 · G1'];return ['Brick City Rockets','Jersey Braves','Big Apple Yankees','Blue Angels','Brick City Rockets'].map((opponent,i)=>({opponent,date:dates[i],us:[s.score[0],7,2,9,5][i],them:[s.score[1],4,5,1,3][i]}))}
function renderScores(){$('#scoreboard-games').innerHTML=recentGames().map((g,i)=>`<button class="scoreboard-game" data-score="${i}" aria-label="${g.date}: Jersey Dodgers ${g.us}, ${g.opponent} ${g.them}. View sample recap"><span class="score-meta"><span>${g.date} · FINAL</span><span class="${g.us>g.them?'result-win':'result-loss'}">${g.us>g.them?'W':'L'}</span></span><span class="score-row"><img src="assets/d-mark.png" alt=""><strong>Jersey Dodgers</strong><b>${g.us}</b></span><span class="score-row opponent-row"><span class="opponent-abbr" aria-hidden="true">${g.opponent.split(' ').map(w=>w[0]).join('')}</span><span>${g.opponent}</span><b>${g.them}</b></span><span class="score-details">Box score & recap ↗</span></button>`).join('')}
const external=(url,label)=>`<a class="button" href="${url}" target="_blank" rel="noopener">${label} ↗</a>`;
const instagram=()=>external('https://www.instagram.com/jerseydodgers/','Visit @jerseydodgers');
function show(title,body){$('#dialog-content').innerHTML=`<h2 id="dialog-title">${title}</h2>${body}`;$('#detail').setAttribute('aria-labelledby','dialog-title');$('#detail').showModal();}
const views={
'all-scores':()=>['Last five Dodgers games',`<p>${seasons[current].name} · Sample results, newest first.</p><table><thead><tr><th>DATE / OPPONENT</th><th>JD</th><th>OPP</th></tr></thead><tbody>${recentGames().map(g=>`<tr><td>${g.date}<br>${g.opponent}</td><td>${g.us}</td><td>${g.them}</td></tr>`).join('')}</tbody></table><p>Choose a game in the top scoreboard to open its sample recap.</p>`],
game:()=>{const s=seasons[current];return [`${s.name} Game Center`,`<span class="sample">SAMPLE GAME · NOT A CONFIRMED FIXTURE</span><h3 style="margin-top:20px">Jersey Dodgers vs. Jersey Braves</h3><p>${s.date}<br>${s.time}</p><p><strong>Vailsburg Park</strong><br><a class="field-directions" href="https://share.google/n9x1kGdETlEc4i7EP" target="_blank" rel="noopener">Directions · Google Maps ↗</a><br>74°F · Partly sunny · Wind W 6 mph · Rain 10%<br><small>Team-supplied field link; sample game and weather, not a real forecast. Lineup and game link await confirmation.</small></p><p>The final version can present inning scores, player performances and a recap in this game center. This preview uses no live connection.</p>`]},
recap:()=>{const a=seasons[current].score[0],b=seasons[current].score[1];return ['Latest result & recap',`<span class="sample">FICTIONAL SAMPLE · ${seasons[current].name.toUpperCase()}</span><table><thead><tr><th>TEAM</th><th>R</th></tr></thead><tbody><tr><td>Jersey Dodgers</td><td>${a}</td></tr><tr><td>Brick City Rockies</td><td>${b}</td></tr></tbody></table><h3>Dodgers finish strong</h3><p>In this sample recap, the Dodgers combine timely hitting with steady pitching to close out a ${a}–${b} win. This is illustrative copy, not a report of an actual game.</p><p>A verified inning-by-inning box score and player performances will replace this sample.</p>`]},
standings:()=>['Division standings',`<p>${seasons[current].name} · Fictional preview standings.</p><table><thead><tr><th>TEAM</th><th>W</th><th>L</th><th>PCT</th><th>GB</th></tr></thead><tbody>${rows()}</tbody></table><p>This compact sample table demonstrates the league data layout. The confirmed full division and records would come from PrimeTime.</p>`],
roster:()=>['Meet the Dodgers',`<p>${seasons[current].name} · Fictional roster sample. Team headshots and verified player information will replace these entries.</p><table><thead><tr><th>PLAYER</th><th>NO.</th><th>POS.</th></tr></thead><tbody>${[['Alex Rivera',24,'OF'],['Marcus Torres',17,'1B'],['Daniel Cruz',9,'SS'],['Chris Bennett',2,'CF'],['Luis Santos',31,'RHP'],['Mike Rossi',12,'LHP']].map(([n,no,p])=>`<tr><td><button class="text-button" data-player="${n}">${n} ↗</button></td><td>${no}</td><td>${p}</td></tr>`).join('')}</tbody></table>`],
hot:()=>['Hot Dodgers · Last five',`<p>${seasons[current].name} · Fictional performance sample.</p><h3>Alex Rivera · #24</h3><p>${seasons[current].avg} AVG · ${current==='fall'?10:current==='spring'?9:11} hits · 7 RBI</p><p>This section highlights recent form separately from full-season statistics. The sample team form is W–W–L–W–W, oldest to newest.</p>`],
championship:()=>['2025. In the history books.',`<span class="eyebrow" style="color:#d7be8d">JERSEY DODGERS · 2025 REGULAR SEASON CHAMPIONS</span><img class="championship-dialog-poster" src="assets/2025-champions.jpg" alt="Jersey Dodgers 2025 regular season champions team poster"><p>The 2025 regular season championship belongs in the Dodgers trophy case. Celebrating the team that made it happen.</p><p>Team poster supplied by the Jersey Dodgers. Additional season records and player details will be added when confirmed.</p>`],
'media-season':()=>['The next chapter starts here.',`<span class="sample">SAMPLE EDITORIAL</span><p>Fall brings another chance to put Jersey on the field. This space will introduce the new season, key matchups and the team’s goals.</p><p>Official dates, roster announcements and team photos are still to come.</p>`],
'media-brand':()=>['Jersey across the chest.',`<img src="assets/jersey-dodgers.png" alt="Jersey Dodgers script logo" style="width:100%;max-height:260px"><p>Black and charcoal. Dodger blue. A shot of red. The original team script and D/baseball mark anchor the club’s identity.</p>`],
'media-social':()=>['Inside the clubhouse',`<p>Team photos, game-day moments and reels will appear here. These cards are editorial placements, not posts pulled from Instagram.</p>${instagram()}`],
sponsor:()=>['Put your brand in our corner.',`<p>Sponsor placements are available in this preview. No displayed placeholder represents a confirmed sponsor.</p><ul><li>Presenting partner: prominent homepage placement</li><li>Community partner: local business recognition</li><li>Team partner: support the Dodgers season</li></ul><p>Contact the team on Instagram to discuss sponsorship. No inquiry is sent by this preview.</p>${instagram()}`],
tryouts:()=>['Your next inning starts here.',`<p>Interested in joining the Jersey Dodgers? Tryout dates, location, eligibility and roster needs have not been confirmed for this preview.</p><p>Contact the team on Instagram and include your name, playing position and baseball experience.</p>${instagram()}<p><small>This opens the official profile. Nothing is submitted or sent automatically.</small></p>`],
sources:()=>['The data behind the clubhouse',`<p>This is a standalone design preview. No scores, standings or player statistics are synced.</p><ul><li><strong>GameChanger:</strong> intended placement for game details and player statistics, once a suitable authorized connection or import is configured.</li><li><strong>PrimeTime:</strong> intended placement for official league schedules and standings.</li><li><strong>Team archive:</strong> championships, photos and club history.</li></ul>${external('https://web.gc.com/teams/1sMI1Y0GzHLE/2026-spring-jersey-dodgers/team','Spring 2026 GameChanger')}${external('https://www.primetimebaseballleague.com/teams/?u=PRIMETIMEBASEBALLLEA&s=baseball','PrimeTime league')}<p>These are source links supplied in the team brief. Fall 2026 GameChanger is not yet linked.</p>`]
};
document.addEventListener('click',e=>{const score=e.target.closest('[data-score]');if(score){const g=recentGames()[Number(score.dataset.score)];show('Game result & recap',`<span class="sample">FICTIONAL SAMPLE · ${seasons[current].name.toUpperCase()}</span><p>${g.date} · Final / 7 innings</p><table><thead><tr><th>TEAM</th><th>RUNS</th></tr></thead><tbody><tr><td>Jersey Dodgers</td><td>${g.us}</td></tr><tr><td>${g.opponent}</td><td>${g.them}</td></tr></tbody></table><h3>${g.us>g.them?'Dodgers take the win':'Dodgers look to bounce back'}</h3><p>In this illustrative game, Jersey finishes with ${g.us} runs against ${g.opponent}’ ${g.them}. This is sample content, not an actual game report.</p><p>Verified inning scores and individual performances will appear here when available.</p>`);return}const player=e.target.closest('[data-player]');if(player){const name=player.dataset.player;if($('#detail').open)$('#detail').close();show(name,`<span class="sample">FICTIONAL PLAYER PROFILE</span><p>${seasons[current].name} · Jersey Dodgers</p><p>This profile demonstrates where an official headshot, position, season statistics, career history and game log will appear.</p><p>The name and numbers shown in the homepage preview are sample content.</p>`);return}const button=e.target.closest('[data-view]');if(button&&views[button.dataset.view]){const [title,body]=views[button.dataset.view]();show(title,body)}});
$('#close-dialog').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#detail').close()}});
renderSeason();

// Scroll controls for the compact scoreboard, including keyboard activation.
const scoreTrack=document.querySelector('#scoreboard-games');
const scoreButtons=document.querySelectorAll('.score-scroll');
function updateScoreControls(){scoreButtons.forEach(button=>{button.disabled=Number(button.dataset.direction)<0?scoreTrack.scrollLeft<=1:scoreTrack.scrollLeft+scoreTrack.clientWidth>=scoreTrack.scrollWidth-2})}
scoreButtons.forEach(button=>button.addEventListener('click',()=>{const card=scoreTrack.querySelector('.scoreboard-game');scoreTrack.scrollBy({left:Number(button.dataset.direction)*((card?card.getBoundingClientRect().width:200)+9),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}));
scoreTrack.addEventListener('scroll',updateScoreControls,{passive:true});
window.addEventListener('resize',updateScoreControls);
window.addEventListener('load',updateScoreControls);
new MutationObserver(updateScoreControls).observe(scoreTrack,{childList:true});
updateScoreControls();
