import {getUser,admin,verifyRequestOrigin} from '@netlify/identity';

const TEAM='Jersey Dodgers';
const DEFAULT_URL='https://www.primetimebaseballleague.com/teams/default.asp?u=PRIMETIMEBASEBALLLEA&s=baseball&p=schedule&format=List&d=ALL';
const KNOWN_TEAM_URLS=[
 'https://www.primetimebaseballleague.com/teams/default.asp?p=schedule&playerID=1013439&s=baseball&u=PRIMET-C--NJWHITESOX&format=List&d=ALL',
 'https://www.primetimebaseballleague.com/teams/default.asp?p=schedule&s=baseball&u=PRIMET-C--NJWHITESOX&format=List&d=ALL'
];
const rolesFor=(user:any)=>[...(Array.isArray(user?.roles)?user.roles:[]),...(Array.isArray(user?.appMetadata?.roles)?user.appMetadata.roles:[]),...(user?.role?[user.role]:[])];
const canManage=(user:any)=>{const roles=rolesFor(user),owner=(Netlify.env.get('DODGERS_ADMIN_EMAIL')||'').toLowerCase();return Boolean(user?.id&&(((user.email||'').toLowerCase()===owner)||roles.includes('dodgers-owner')||roles.includes('dodgers-coach')))};
const decode=(v:string)=>String(v||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&#x27;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)));
const textOf=(html:string)=>decode(String(html||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());
const textLines=(html:string)=>decode(String(html||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<\/(?:tr|li|article|section|div|p|h[1-6])\s*>/gi,'\n').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s*\n+/g,'\n').trim());
const norm=(v:string)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const seasonInfo=(text:string)=>{const m=String(text).match(/\b(Fall|Spring|Summer|Winter)\s+(20\d{2})\b/i)||String(text).match(/\b(20\d{2})\s+(Fall|Spring|Summer|Winter)\b/i);if(!m)return null;const term=/^20/.test(m[1])?m[2]:m[1],year=/^20/.test(m[1])?m[1]:m[2],pretty=term[0].toUpperCase()+term.slice(1).toLowerCase();return{name:`${pretty} ${year}`,year,term:pretty}};
function isoDate(value:string,year=''){const v=String(value||'').trim();let m=v.match(/\b(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})\b/);if(m){const y=m[3].length===2?`20${m[3]}`:m[3];return `${y}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`}m=v.match(/\b(?:Sun|Mon|Tue|Wed|Thu|Fri|Sat)?\s*,?\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*\s+(\d{1,2})(?:,?\s*(20\d{2}))?/i);if(!m)return'';const months:any={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,sept:9,oct:10,nov:11,dec:12};return `${m[3]||year||new Date().getFullYear()}-${String(months[m[1].toLowerCase()]).padStart(2,'0')}-${m[2].padStart(2,'0')}`}
function time24(value:string){const v=String(value||'');let m=v.match(/\b(\d{1,2}):(\d{2})\s*(AM|PM)\b/i);if(m){let h=Number(m[1]);if(m[3].toUpperCase()==='PM'&&h!==12)h+=12;if(m[3].toUpperCase()==='AM'&&h===12)h=0;return `${String(h).padStart(2,'0')}:${m[2]}`}m=v.match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:''}
const cleanTeam=(v:string)=>String(v||'').replace(/^\s*@\s*/,'').replace(/^\s*(?:vs\.?|at)\s+/i,'').replace(/\s+/g,' ').trim();
const likelyNonTeam=(v:string)=>/^(date|time|home|away|visitor|team|opponent|field|location|venue|status|result|score|game|division|league|details|schedule)$/i.test(String(v).trim())||!!isoDate(v)||!!time24(v)||/^\d+[-:]\d+$/.test(String(v).trim());
function headerIndexes(cells:string[]){const l=cells.map(v=>v.toLowerCase());const find=(re:RegExp)=>l.findIndex(x=>re.test(x));return{date:find(/^date$|game date/),time:find(/^time$|start/),home:find(/^home$|home team/),away:find(/^away$|visitor|visiting/),opponent:find(/opponent/),field:find(/field|location|venue|park/)};}
function teamContext(html:string){const title=textOf(html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]||''),heads=[...html.matchAll(/<h[1-4]\b[^>]*>([\s\S]*?)<\/h[1-4]>/gi)].slice(0,12).map(m=>textOf(m[1])).join(' · ');return /jersey\s*dodgers/i.test(`${title} ${heads}`)&&/schedule/i.test(`${title} ${heads}`)}
function parseTables(html:string,seasonYear=''){
 const out:any[]=[],context=teamContext(html),tables=[...html.matchAll(/<table\b[^>]*>([\s\S]*?)<\/table>/gi)].map(m=>m[1]);
 for(const table of tables){let header:any=null;for(const rm of table.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...rm[1].matchAll(/<(?:th|td)\b[^>]*>([\s\S]*?)<\/(?:th|td)>/gi)].map(m=>textOf(m[1])).filter(Boolean);if(cells.length<2)continue;const joined=cells.join(' | '),idx0=headerIndexes(cells);if(!header&&Object.values(idx0).filter(v=>Number(v)>=0).length>=2&&/date|time|home|away|visitor|opponent|field|location/i.test(joined)){header=idx0;continue}const idx=header||idx0,date=idx.date>=0?isoDate(cells[idx.date],seasonYear):isoDate(joined,seasonYear),time=idx.time>=0?time24(cells[idx.time]):time24(joined);if(!date)continue;
   let home=idx.home>=0?cleanTeam(cells[idx.home]||''):'',away=idx.away>=0?cleanTeam(cells[idx.away]||''):'',opponent=idx.opponent>=0?String(cells[idx.opponent]||'').trim():'';const hasJD=/jersey\s*dodgers/i.test(joined);
   if(!hasJD&&!context)continue;
   let isHome=false;
   if(home||away){isHome=/jersey\s*dodgers/i.test(home);const isAway=/jersey\s*dodgers/i.test(away);opponent=isHome?away:isAway?home:opponent;if(!isHome&&!isAway&&context&&opponent)isHome=!/^@/.test(opponent)}
   if(!opponent&&context){const candidates=cells.filter(c=>!likelyNonTeam(c)&&/[A-Za-z]/.test(c)&&!/jersey\s*dodgers/i.test(c)&&c.length<90);opponent=candidates.find(c=>!/(final|scheduled|postponed|cancel)/i.test(c))||'';isHome=!/^@/.test(opponent)}
   if(!opponent&&hasJD){const candidates=cells.filter(c=>!likelyNonTeam(c)&&/[A-Za-z]/.test(c)&&!/jersey\s*dodgers/i.test(c)&&c.length<90);opponent=candidates[0]||''}
   let field=idx.field>=0?cells[idx.field]||'':'';if(!field)field=cells.find(c=>/(field|park|stadium|ballpark|complex|school)/i.test(c)&&!/jersey\s*dodgers/i.test(c))||'';
   opponent=cleanTeam(opponent);if(opponent&&norm(opponent)!==norm(TEAM))out.push({date,time,home:isHome,opponent,field:String(field||'').trim(),raw:joined});
  }}return out;
}
function parseLoose(text:string,seasonYear='',context=false){const out:any[]=[];for(const raw of String(text||'').split(/\r?\n/)){const line=raw.replace(/\s+/g,' ').trim();if(!line)continue;const date=isoDate(line,seasonYear);if(!date)continue;const hasJD=/jersey\s*dodgers/i.test(line);if(!hasJD&&!context)continue;const time=time24(line);let opponent='';const versus=line.match(/(?:Jersey\s+Dodgers\s+(?:vs\.?|at|@)\s*|(?:vs\.?|at|@)\s*Jersey\s+Dodgers\s+)([A-Za-z0-9 &'’.\-]+?)(?=\s{2,}|\s(?:\d{1,2}:\d{2}|Field|Park|Stadium|School|$))/i);if(versus)opponent=versus[1];if(!opponent&&context){const after=line.replace(/^.*?\b(?:AM|PM)\b/i,'').trim(),parts=after.split(/\s{2,}|\s+\|\s+/).filter(Boolean);opponent=parts.find(p=>!likelyNonTeam(p)&&/[A-Za-z]/.test(p)&&!/jersey\s*dodgers/i.test(p)&&p.length<90)||''}if(!opponent&&hasJD){const parts=line.split(/\s{2,}|\s+\|\s+/).filter(Boolean);opponent=parts.find(p=>!likelyNonTeam(p)&&/[A-Za-z]/.test(p)&&!/jersey\s*dodgers/i.test(p)&&p.length<90)||''}opponent=cleanTeam(opponent);if(opponent)out.push({date,time,home:!/@\s*Jersey Dodgers/i.test(line)&&!/\bJersey Dodgers\s+at\b/i.test(line),opponent,field:(line.match(/([A-Za-z0-9 .'-]+(?:Field|Park|Stadium|Ballpark|Complex|School))/i)?.[1]||'').trim(),raw:line})}return out;}
function dedupeAndClassify(rows:any[]){const map=new Map<string,any>();for(const r of rows){if(!r.date||!r.opponent)continue;const key=[r.date,r.time,norm(r.opponent),norm(r.field),r.home?'H':'A'].join('|');if(!map.has(key))map.set(key,r)}const out=[...map.values()].sort((a,b)=>a.date.localeCompare(b.date)||String(a.time).localeCompare(String(b.time)));const groups=new Map<string,any[]>();for(const g of out){const key=[g.date,norm(g.opponent),norm(g.field),g.home?'H':'A'].join('|');if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(g)}for(const items of groups.values()){items.sort((a,b)=>String(a.time).localeCompare(String(b.time)));if(items.length>=2)items.slice(0,2).forEach((g,i)=>Object.assign(g,{seriesType:'doubleheader',gameNumber:i+1,innings:7}));else Object.assign(items[0],{seriesType:'single',gameNumber:1,innings:9})}return out;}
async function fetchPage(url:string){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),14000);try{const r=await fetch(url,{redirect:'follow',signal:controller.signal,headers:{'User-Agent':'Mozilla/5.0 (compatible; JerseyDodgersScheduleImporter/2.0)','Accept':'text/html,application/xhtml+xml'}});if(!r.ok)throw Error(`PrimeTime returned ${r.status}.`);return await r.text()}finally{clearTimeout(timer)}}
function candidateUrls(html:string,base:string){const set=new Set<string>();for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const label=textOf(m[2]);if(!/jersey\s*dodgers/i.test(label)&&!/PRIMET-C--NJWHITESOX/i.test(m[1]))continue;try{const u=new URL(decode(m[1]),base);u.searchParams.set('p','schedule');u.searchParams.set('s','baseball');u.searchParams.set('format','List');u.searchParams.set('d','ALL');set.add(u.toString())}catch{}}
 for(const m of html.matchAll(/<iframe\b[^>]*src=["']([^"']+)["']/gi)){try{const u=new URL(decode(m[1]),base);if(/primetimebaseballleague\.com/i.test(u.hostname))set.add(u.toString())}catch{}}
 KNOWN_TEAM_URLS.forEach(u=>set.add(u));return [...set];}
function parsePage(html:string){const title=textOf(html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]||''),lines=textLines(html),season=seasonInfo(title)||seasonInfo(lines),year=season?.year||'';let games=parseTables(html,year);if(!games.length)games=parseLoose(lines,year,teamContext(html));return{season,games:dedupeAndClassify(games)}}

export default async(req:Request)=>{const headers={'Cache-Control':'no-store','Content-Type':'application/json'},respond=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers});try{let user=await getUser();try{if(user?.id)user=await admin.getUser(user.id)}catch{}if(!canManage(user))return respond({error:'Coach/Admin access required.'},403);if(req.method!=='POST')return respond({error:'Method not allowed'},405);verifyRequestOrigin(req);const body=await req.json(),url=String(body.url||DEFAULT_URL).trim(),pasted=String(body.text||'').trim();let parsed:URL;try{parsed=new URL(url)}catch{return respond({error:'Enter a valid PrimeTime schedule URL.'},400)}if(parsed.protocol!=='https:'||!/(^|\.)primetimebaseballleague\.com$/i.test(parsed.hostname))return respond({error:'Use a PrimeTimeBaseballLeague.com https:// schedule link.'},400);
 if(pasted){const fake=`<title>${TEAM}</title>\n${pasted}`,parsedText=parsePage(fake);if(!parsedText.games.length)return respond({error:'No Jersey Dodgers games were recognized in the pasted schedule text.'},400);return respond({source:url,sourceType:'pasted',team:TEAM,season:parsedText.season,games:parsedText.games})}
 let firstHtml='';try{firstHtml=await fetchPage(url)}catch(e:any){return respond({error:'PrimeTime blocked the automatic reader or timed out. Paste the Jersey Dodgers schedule rows into the fallback box.',detail:e?.message||''},502)}
 let parsedPage=parsePage(firstHtml),used=url;
 if(!parsedPage.games.length){for(const candidate of candidateUrls(firstHtml,url)){if(candidate===url)continue;try{const html=await fetchPage(candidate),next=parsePage(html);if(next.games.length){parsedPage=next;used=candidate;break}}catch{}}}
 if(!parsedPage.games.length)return respond({error:'PrimeTime loaded, but no Jersey Dodgers game rows were exposed to the server. Use the fallback box: copy the Jersey Dodgers schedule rows from PrimeTime and paste them here. The review/matching step will still reuse your teams, logos and fields.'},400);
 return respond({source:url,readFrom:used,sourceType:used===url?'live':'team-page-fallback',team:TEAM,season:parsedPage.season,games:parsedPage.games});
 }catch(e:any){return respond({error:e?.message||'Unable to read the PrimeTime schedule.'},500)}};
export const config={path:'/api/admin/primetime-schedule'};
