const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function pastedTable(value){
 const blocks=String(value||'').trim().split(/\n\s*\n/);if(blocks.length>1)return blocks.map(pastedTable).join('');
 const lines=String(value||'').trim().split(/\r?\n/).filter(l=>l.trim());if(!lines.length)return '';
 const rows=lines.map(l=>l.trim().split(/\t+|\s*\|\s*| {2,}/).filter(Boolean));
 if(rows.length>1&&rows[0].length>1&&rows.every(r=>r.length===rows[0].length))return `<div class="recap-table-scroll" tabindex="0" aria-label="Scrollable box score"><table><thead><tr>${rows[0].map(c=>`<th scope="col">${escape(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(r=>`<tr>${r.map((c,i)=>i?`<td>${escape(c)}</td>`:`<th scope="row">${escape(c)}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 return `<pre class="recap-score-text">${escape(value)}</pre>`;
}
export function recapArticle(r){
 const source=/^https:\/\//i.test(r.source||'')?`<a class="button" href="${escape(r.source)}" target="_blank" rel="noopener">View original on GameChanger ↗</a>`:'';
 return `<article class="recap-article"><header class="recap-heading"><span class="eyebrow">GAME RECAP · ${escape(r.date)}</span><h1>${escape(r.title)}</h1><p>${escape(r.summary)}</p>${r.author?`<small>${escape(r.author)}</small>`:''}</header>${r.ourScore!==null&&r.ourScore!==undefined&&r.theirScore!==null&&r.theirScore!==undefined?`<div class="recap-scoreboard"><div><span>JERSEY DODGERS</span><strong>${escape(r.ourScore)}</strong></div><b>FINAL</b><div><span>${escape(r.opponent)}</span><strong>${escape(r.theirScore)}</strong></div></div>`:''}${r.image?`<img class="recap-cover" src="${escape(r.image)}" alt="${escape(r.title)}">`:''}<div class="recap-story">${String(r.body||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${escape(p).replace(/\n/g,'<br>')}</p>`).join('')}</div>${r.lineScore?`<section class="recap-box"><h2>Inning by inning</h2>${pastedTable(r.lineScore)}</section>`:''}${r.boxScore?`<section class="recap-box"><h2>Box score</h2>${pastedTable(r.boxScore)}</section>`:''}<footer class="recap-source">${source}</footer></article>`;
}
export function recapCards(posts){return `<div class="recap-grid">${posts.map(r=>`<a class="recap-card" href="/recaps/${encodeURIComponent(r.id)}/">${r.image?`<img src="${escape(r.image)}" alt="" loading="lazy">`:''}<div><span class="eyebrow">${escape(r.date)} · GAME RECAP</span><h3>${escape(r.title)}</h3>${r.ourScore!==null&&r.ourScore!==undefined&&r.theirScore!==null&&r.theirScore!==undefined?`<strong>Dodgers ${escape(r.ourScore)} — ${escape(r.opponent)} ${escape(r.theirScore)}</strong>`:''}<p>${escape(r.summary||String(r.body||'').slice(0,150))}</p><span>Read the recap →</span></div></a>`).join('')}</div>`}
